### ISSUE TITLE
Having issues with automagic uploads/logging

### ISSUE THREAD

**Issue by JHenzi** [seanauff/node-red-torque#2]
Sean this is great work but I'm not seeing the data flow into Influx. Not sure where the breakdown is but was wondering if I can do some manual testing by posting data into the node red endpoint and seeing where this might go. 

Very new to this, so wasn't sure of the output format from Torque in the logging push if I could use their exported reports as a basis to debug/troubleshoot.

**Comment by seanauff** [comment]
@JHenzi glad to see someone getting use out of this! The node-red flow contains an "Inject" node (I named it "testdata") that bypasses Torque entirely and lets you see if the back-end side of the system is working properly.  So you should be able to use that to do some manual testing.

**Comment by JHenzi** [comment]
Sean, I actually tested this with Curl and I get the error 'Cannot POST' instead, so I'm really lost. Sorry it's my first foray into Node red because this is exactly what I was trying to solve. Maybe I'll keep digging. 

I'm trying to post to URL:port/upload

**Comment by seanauff** [comment]
@JHenzi No worries! The HTTP input node is actually set to GET, not POST (a little weird, but that's what the Torque app sends).

**Comment by JHenzi** [comment]
I swore I tried that, but I did it again from the command line and received no error. I'll keep playing, thanks Sean!

**Comment by JHenzi** [comment]
Sean, I got it working, Torque -> NodeRed -> MQTT -> Telegraf -> Grafana

Building the first dashboard now, exciting stuff. Very happy, love your flow. Turns out my issue was in Telegraf. Can't wait to start pushing some to Home Assistant as well. Fun stuff, excited!

**Comment by seanauff** [comment]
Great, glad you found it useful!
